name: Publish Hello World to Callback
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Cortex Callback URL"
        required: true
        type: string

env:
  CORTEX_API_KEY: ${{ secrets.CORTEX_XYCIACORTEX_KEY }}

jobs:
  async-callback:
    runs-on: ubuntu-latest
    steps:
      - name: Display Callback URL
        run: |
          echo "Callback URL: ${{ github.event.inputs.url }}"

      - name: Write data to callback URL
        run: |
          (cat << EOF
          {
            "message": "This is the message.",
            "response": {
              "foo": "bar"
            },
            "status": "SUCCESS"
          }
          EOF
          ) | curl \
            -vvv \
            --fail-with-body \
            --data @- \
            -H "Content-Type: application/json;charset=UTF-8" \
            -H "Authorization: Bearer ${CORTEX_API_KEY}" \
            ${{ github.event.inputs.url }}
